# Generated by Django 4.2.17 on 2025-04-25 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0008_alter_menumodel_links_alter_pagemodel_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menumodel",
            name="text",
            field=models.CharField(
                help_text="The tiel (or name) of your reference",
                max_length=50,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=50, message="Max length (of title) 50 symbols"
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3, message="Min length (of title) 3 symbols"
                    ),
                    django.core.validators.RegexValidator(
                        message="The title not have correct format.",
                        regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w \\-_\\dа-яА-ЯёЁ]{1,48}[a-zA-Zа-яА-ЯёЁ]$[^\\S\\W \\\\]?",
                    ),
                ],
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="pagemodel",
            name="text",
            field=models.CharField(
                help_text="The tiel (or name) of your reference",
                max_length=50,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=50, message="Max length (of title) 50 symbols"
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3, message="Min length (of title) 3 symbols"
                    ),
                    django.core.validators.RegexValidator(
                        message="The title not have correct format.",
                        regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w \\-_\\dа-яА-ЯёЁ]{1,48}[a-zA-Zа-яА-ЯёЁ]$[^\\S\\W \\\\]?",
                    ),
                ],
                verbose_name="Title",
            ),
        ),
    ]
