# Generated by Django 4.2.17 on 2025-04-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0009_alter_menumodel_text_alter_pagemodel_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menumodel",
            name="links",
        ),
        migrations.RemoveField(
            model_name="menumodel",
            name="text",
        ),
    ]
