# Generated by Django 4.2.17 on 2025-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0011_alter_pagemodel_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagemodel",
            name="template",
            field=models.CharField(
                choices=[
                    ("index.html", "Главная"),
                    ("about/index.html", "О нас"),
                    ("contacts/index.html", "Контакты"),
                    ("profile/index.html", "Профиль"),
                    ("404/index.html", "404"),
                ],
                default="404/index.html",
                verbose_name="Choose the page's template",
            ),
        ),
    ]
