# Generated by Django 4.2.17 on 2025-04-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0012_alter_pagemodel_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menumodel",
            name="level",
            field=models.CharField(
                choices=[
                    ("TOP", "Верхний"),
                    ("SIDE", "Боковой"),
                    ("BOTTOM", "Нижний"),
                    ("PLUG", "Заглушка"),
                ],
                default="TOP",
                verbose_name="Level manu",
            ),
        ),
    ]
