# Generated by Django 4.2.17 on 2025-04-26 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0013_alter_menumodel_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuLinksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linksPages",
                        to="menu_app.menumodel",
                    ),
                ),
                (
                    "pages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linksPages",
                        to="menu_app.pagemodel",
                    ),
                ),
            ],
        ),
    ]
