# Generated by Django 4.2.17 on 2025-04-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0015_remove_pagemodel_menu_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPageModel',
            fields=[
                ('pagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu_app.pagemodel')),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpages', to='menu_app.pagemodel')),
            ],
            options={
                'verbose_name': 'Base Menu Link',
                'verbose_name_plural': 'Base Menu Links',
                'abstract': False,
            },
            bases=('menu_app.pagemodel',),
        ),
    ]
