# Generated by Django 4.2.17 on 2025-04-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0018_alter_subpagemodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpagemodel',
            name='parent',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
