# Generated by Django 4.2.17 on 2025-04-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0019_alter_subpagemodel_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subpagemodel',
            options={'verbose_name': 'Subpage', 'verbose_name_plural': 'Subpages'},
        ),
    ]
